baseURL = "/"
languageCode = "en-us"
title = "E4"
theme = "techdoc"

pygmentsCodeFences = true
pygmentsstyle = "solarized-dark"

[Params]
    # Source code repository section
    description = "Secure IoT communications library"
    github_repository = "https://github.com/teserakt-io/e4go"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/teserakt-io/e4-doc"

    # path name excluded from documentation menu
    menu_exclusion = []
