baseURL = "/"
languageCode = "en-us"
title = "E4"
theme = "techdoc"

[Params]
    # Souce Code repository section
    description = "Lightweight and secure IoT communications library"
    github_repository = "https://github.com/Teserakt-io/e4"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/Teserakt-io/e4-doc"

    # path name excluded from documentation menu
    menu_exclusion = []
