name: Hugo
on:
  push:
    branches: master

jobs:
  build:
    name: Hugo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./.github/actions/hugo

      - uses: actions/upload-artifact@master
        with:
          name: e4-doc
          path: public/
